### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by xizaoqu** [Drexubery/ViewCrafter#1]
Hi, very nice work.

May I ask if you could release the training scripts on this model? Was this model based on some fundamental models (like videocrafter) ?

Thanks.

**Comment by Drexubery** [comment]
Thanks! The model is finetuned from DynamiCrafter [https://github.com/Doubiiu/DynamiCrafter](url).
We are currently refining the dataset creation and training scripts, you can also refer to their training code.

**Comment by xizaoqu** [comment]
Thanks for your explanation.

**Comment by sudonymously** [comment]
Hi! Really been loving the potential of this project. will you release the dataset creation and training code?

**Comment by Drexubery** [comment]
Yes, it's on our schedule.

sudo ***@***.***>于2024年9月28日 周六02:04写道：
