### ISSUE TITLE
Questions about cases on dynamic video NVS

### ISSUE THREAD

**Issue by xizaoqu** [Drexubery/ViewCrafter#11]
Hi, thanks for sharing the great work.

When testing, I find that some cases will result in weird quality, do you have some insights about this?

https://github.com/user-attachments/assets/cb0013a6-ab9a-494f-a114-3482e2ea785a

https://github.com/user-attachments/assets/45aabf9a-f59b-4ffc-931a-2a79062e17a8

**Comment by Drexubery** [comment]
Hi, our model is designed to handle static images rather than dynamic videos. We will release a model for video NVS soon; please stay tuned.

**Comment by lebron12332** [comment]
@xizaoqu 
Hi, I would like to ask what do you use as prompt to generate this video, is it a single image with text as prompt？

**Comment by lebron12332** [comment]
@Drexubery 
Hello author, what does video NVS mean? What are the input and output respectively? When will it be released? Can you give me an approximate time?

**Comment by xizaoqu** [comment]
> Hi, our model is designed to handle static images rather than dynamic videos. We will release a model for video NVS soon; please stay tuned.

Thanks.

**Comment by xizaoqu** [comment]
> you use as prompt to generate this video, is it a single image with text as promp

Hi, it is a video from the DAVIS dataset.

**Comment by lebron12332** [comment]
@xizaoqu Thank you for your reply! Sorry to bother you again. Do you mean that the input is a video？(I'm curious because the viewcrafer currently only supports a single image as input.)

**Comment by xizaoqu** [comment]
> @xizaoqu Thank you for your reply! Sorry to bother you again. Do you mean that the input is a video？(I'm curious because the viewcrafer currently only supports a single image as input.)

The origin input is an image, but it will process it into a video (you can check the output file/rendering.mp4).

**Comment by lebron12332** [comment]
@xizaoqu Thanks again!
