### ISSUE TITLE
Work with other point cloud generation models and diffusion models?

### ISSUE THREAD

**Issue by LearnedVector** [Drexubery/ViewCrafter#13]
Would this method work with other point cloud models like Mast3R and video diffusion models like CogVideoX-5B? Or is this technique unique to only Dust3r and DynamicCrafter models

**Comment by Drexubery** [comment]
Hi, we utilize off-the-shelf dense stereo methods to construct point clouds in our method; Therefore, it can be replaced with any stronger model like Mast3R. The video diffusion model cannot be altered to CogVideoX-5B because our model is finetuned from DynamiCrafter.

**Comment by LearnedVector** [comment]
Thanks @Drexubery. but technically i can also replace DynamiCrafter with CogVideoX-5B and finetune it?

**Comment by Drexubery** [comment]
> Thanks @Drexubery. but technically i can also replace DynamiCrafter with CogVideoX-5B and finetune it?

Yes
