### ISSUE TITLE
Question about upcoming sparse-view novel view synthesis and iterative novel view synthesis

### ISSUE THREAD

**Issue by tsuJohc** [Drexubery/ViewCrafter#14]
Hi, thanks for releasing such amazing work!

I am curious about the upcoming sparse-view nvs and iterative nvs.

(1) What will be the differences between sparse-view nvs and released single-view nvs? 

In my opinion, only difference is sparse-view nvs need Dust3R to reconstruct two views and maybe need iterative nvs for large baseline?

(2) The **details** of iterative nvs (progressive nvs in paper)? 

The paper didn't tell any details of "we backproject and align the generated novel view onto the current point cloud" after "apply ViewCrafter along the path to generate a sequence of high-fidelity novel views".

I would like to ask **what kind of model is used to get the depths of novel view, still Dust3R? how to align the point clouds of novel views to current point cloud?**

**Comment by Drexubery** [comment]
Thanks!

1. Yes, single-view NVS and sparse-view NVS differ in that the latter requires DUSt3R to reconstruct two or more views.
2. We use the global alignment strategy  provided by DUSt3R to backproject and align the generated novel view onto the current point cloud.
