### ISSUE TITLE
Is it possible to support more camera movements?

### ISSUE THREAD

**Issue by leeooo001** [Drexubery/ViewCrafter#15]
wonderful work!
The current project seems to support only three kinds of camera motion, left and right, up and down, inside and outside, is it possible to support camera panning motion, so that it will be a perfect solution for support any view,

**Comment by Drexubery** [comment]
Hi, I have added the panning motion, please refer to the docs here https://github.com/Drexubery/ViewCrafter/blob/main/docs/render_help.md

**Comment by leeooo001** [comment]
great!!
