### ISSUE TITLE
question about 360° rendering.

### ISSUE THREAD

**Issue by Vincento-Wang** [Drexubery/ViewCrafter#19]
I have not seen any demo of 360 scene rendered results. the max number of generated frames is 16 ? and it can not cover 360° view range ？

**Comment by Drexubery** [comment]
Hi, the max number of generated frames is 25, and it can not cover 360° view range with only a single input view

**Comment by Vincento-Wang** [comment]
> and it can not cover 360° view range with only a single input view

how many input views for 360° reconstruction? 
for example, if I set the 16 frames at every 20° viewpoint, the reconstruction will not to be continues, in this case, does it work ?

**Comment by Yukun-Huang** [comment]
I tried some 360° rendered results by modifying the trajectory. Iterative novel view synthesis might give better results.

https://github.com/user-attachments/assets/f2c77a53-4c3b-4229-ab32-fceb37cd7e56

https://github.com/user-attachments/assets/09725211-48eb-45aa-a2ae-468aeb7dacc8

**Comment by jh27kim** [comment]
@Yukun-Huang Could you please provide the trajectory txt file for 360 rendering?

**Comment by Vincento-Wang** [comment]
> I tried some 360° rendered results by modifying the trajectory. Iterative novel view synthesis might give better results.
> 
>  render0.mp4 
>  diffusion0.mp4

get it ! maybe 360 rendering should be extended to long frames video generation.
