### ISSUE TITLE
Very exciting work! Some questions about this work.

### ISSUE THREAD

**Issue by lebron12332** [Drexubery/ViewCrafter#2]
Very exciting work!

I am very interested in your work, may I ask when other items in TODO can be completed? In addition, will the training data be released?

After reading the paper, there are some confusion as follows:
1）There is a statement: `The point cloud renders are forced to traverse at least one ground-truth view, i.e., to include at least one ground-truth reference image at a random location among the L frames.` 
But in the `Camera trajectory planning`, `interpolate a camera path between C_curr and C_nbv` seems to be no guarantee of the above statement. In other words, it seems that the reference image cannot be guaranteed on the path of this interpolation.

2）After novel views are generated, the next step is to get a more complete point cloud. Since we do not know the depth map of the novel view, we need to re-run the DUSt3R on all the views to get the new point cloud. Is my understanding correct?

3）May I ask how long it takes to optimize the 3DGS?

4）How about training cost of viewcrafter?

**Comment by Drexubery** [comment]
Thanks!

We are still working hard on cleaning the code, please stay tuned.
1. Yes, the camera trajectory planning algorithm can only ensure that the ground truth reference will be traversed in the first step. After the first step, we use the last generated frame as the newly added pseudo reference, and make it the start point of the next step.
2. Yes, your understanding is correct.
3. It takes about 2 minutes.
4. We use 8 A100 (40G) to train ViewCrafter.

**Comment by lebron12332** [comment]
Thank you very much for your reply and look forward to the full code release!
