### ISSUE TITLE
dynamic video NVS

### ISSUE THREAD

**Issue by zhw-zhang** [Drexubery/ViewCrafter#37]
Hi, thank you for your great work. I saw in a previous issue that you're working on dynamic video NVS, and I'm curious about what "dynamic video" refers to in this context. Does it mean the model takes a video with object motion (and possibly some camera movement within the original video) as input, and outputs a video with specified camera poses while preserving the original object's motion?

**Comment by Drexubery** [comment]
Hi, thanks for your interest.

Yes, here are some examples:

https://github.com/user-attachments/assets/58376a2f-0574-488a-8673-e1a1b0a81a9a

**Comment by zhw-zhang** [comment]
> Hi, thanks for your interest.
> 
> Yes, here are some examples:
> 
>  dv.mov

Interesting!!! Do you have a timeline for releasing the dynamic NVS inference code or the paper? I'm also very curious about how it was done and am excited to read your paper! My understanding is as follows: in the first stage, the dynamic video is mapped to the point cloud space (using a tool like monst3r [https://github.com/Junyi42/monst3r]); then the key is in the second stage, where the VDM model for completion is trained.

If my understanding is correct, I'm curious about how the training data for the completion VDM model was constructed. My biggest question is: in the training data, how do you simulate the missing sparse point cloud in a new view under dynamic video conditions? This would help bridge the gap between training and inference. As mentioned in ViewCrafter 4.1: “Then, we randomly select the constructed point cloud of the video frames and render it along the estimated camera trajectory using Pytorch3D.”

**Comment by Drexubery** [comment]
@zhw-zhang Thanks! 

The results presented above are preliminary, and we are actively working to enhance the dynamic NVS model's performance. Details regarding the code and the dataset creation will be disclosed in an upcoming article. Please stay tuned.

**Comment by zhw-zhang** [comment]
> @zhw-zhang Thanks!
> 
> The results presented above are preliminary, and we are actively working to enhance the dynamic NVS model's performance. Details regarding the code and the dataset creation will be disclosed in an upcoming article. Please stay tuned.

Thank you for your kind response. I was wondering if there is a planned release date for the paper. This would be important for my future research plan. Thanks again!
