### ISSUE TITLE
What is the base model of Viewcrafter and it's training strategy?

### ISSUE THREAD

**Issue by ZyLieee** [Drexubery/ViewCrafter#40]
Thank you for your excellent work! I’m curious about the base model used in the paper. Could you also clarify which specific module(s) are set to be trained? Is it all modules, or only certain ones that are trainable?

**Comment by Drexubery** [comment]
Thanks!

The base model is DynamiCrafter. As stated in the paper, we fine-tune the spatial and temporal layers of the video denoising U-Net while freezing all other components during training
