### ISSUE TITLE
black areas are not filled

### ISSUE THREAD

**Issue by q728yl** [Drexubery/ViewCrafter#50]
I took these pictures on your homepage for inference but found that there are still a lot of black information missing areas that have not been filled in properly, what is the reason for this?

https://github.com/user-attachments/assets/aa9f8ae6-d324-4327-928a-df3772906ca8

https://github.com/user-attachments/assets/715eaa4e-35c0-47c7-bcd6-2b58788c1573

https://github.com/user-attachments/assets/4a85d39e-f346-4e88-a7a8-08d91e6219a2

**Comment by q728yl** [comment]
The command I use is roughly like this：python inference.py --image_dir  ../autodl-tmp/test/images/flower.png --out_dir ../autodl-tmp/output --traj_txt ../autodl-tmp/test/trajs/loop3.txt --mode 'single_view_txt' --center_scale 1. --elevation 5 --seed 123 --d_theta -30 --d_phi 45 --d_r -.2 --d_x 50 --d_y 25 --ckpt_path ../autodl-tmp/checkpoints/DynamiCrafter_1024/model.ckpt --config configs/inference_pvd_1024.yaml --ddim_steps 50 --video_length 16 --device 'cuda:0' --height 576 --width 1024 --model_path ../autodl-tmp/checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth

It feels like no new content is being generated at all？？？

**Comment by Drexubery** [comment]
Have you downloaded the pretrained viewcrafter model and placed it properly?
