### ISSUE TITLE
ERROE：pip install -r requirements.txt 

### ISSUE THREAD

**Issue by RyanSunn** [Drexubery/ViewCrafter#7]
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
![image](https://github.com/user-attachments/assets/278f1b73-196b-4de2-aa1f-21a000a098d5)

**Comment by Drexubery** [comment]
Hi, I can't reproduce this error, can you provide more details? like your python version; Are you using a Windows machine?
